usage: main.py [-h] [--mode {train}] [--template TEMPLATE]
               [--test_model_path TEST_MODEL_PATH]
               [--dataset_code {ml-1m,meli}] [--min_rating MIN_RATING]
               [--min_uc MIN_UC] [--min_sc MIN_SC] [--split SPLIT]
               [--dataloader_code {bert}]
               [--dataloader_random_seed DATALOADER_RANDOM_SEED]
               [--train_batch_size TRAIN_BATCH_SIZE]
               [--val_batch_size VAL_BATCH_SIZE]
               [--test_batch_size TEST_BATCH_SIZE]
               [--train_negative_sampler_code {popular,random}]
               [--train_negative_sample_size TRAIN_NEGATIVE_SAMPLE_SIZE]
               [--train_negative_sampling_seed TRAIN_NEGATIVE_SAMPLING_SEED]
               [--test_negative_sampler_code {popular,random}]
               [--test_negative_sample_size TEST_NEGATIVE_SAMPLE_SIZE]
               [--test_negative_sampling_seed TEST_NEGATIVE_SAMPLING_SEED]
               [--trainer_code {bert}] [--device {cpu,cuda}]
               [--num_gpu NUM_GPU] [--device_idx DEVICE_IDX]
               [--optimizer {SGD,Adam}] [--lr LR]
               [--weight_decay WEIGHT_DECAY] [--momentum MOMENTUM]
               [--decay_step DECAY_STEP] [--gamma GAMMA]
               [--num_epochs NUM_EPOCHS]
               [--log_period_as_iter LOG_PERIOD_AS_ITER]
               [--metric_ks METRIC_KS [METRIC_KS ...]]
               [--best_metric BEST_METRIC] [--model_code {bert}]
               [--model_init_seed MODEL_INIT_SEED]
               [--bert_max_len BERT_MAX_LEN] [--bert_num_items BERT_NUM_ITEMS]
               [--bert_hidden_units BERT_HIDDEN_UNITS]
               [--bert_num_blocks BERT_NUM_BLOCKS]
               [--bert_num_heads BERT_NUM_HEADS] [--bert_dropout BERT_DROPOUT]
               [--bert_mask_prob BERT_MASK_PROB]
               [--experiment_dir EXPERIMENT_DIR]
               [--experiment_description EXPERIMENT_DESCRIPTION]